import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    > 
    <body>
        <StoreProvider>
          <TooltipProvider>
            {children}
          </TooltipProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
