import { classData, Student } from "../type/classType";

export const students: Student[] = [
  {
    id: "ST001",
    profile: "/assets/students/student1.jpg",
    name: "John Doe",
    gender: "Male",
    status: true,
  },
  {
    id: "ST002",
    profile: "/assets/students/student2.jpg",
    name: "Sophia Kim",
    gender: "Female",
    status: false,
  },
  {
    id: "ST003",
    profile: "/assets/students/student3.jpg",
    name: "David Smith",
    gender: "Male",
    status: "late",
  },
  {
    id: "ST004",
    profile: "/assets/students/student4.jpg",
    name: "Emma Watson",
    gender: "Female",
    status: true,
  },
  {
    id: "ST005",
    profile: "/assets/students/student5.jpg",
    name: "Michael Lee",
    gender: "Male",
    status: false,
  },
  {
    id: "ST006",
    profile: "/assets/students/student6.jpg",
    name: "Olivia Brown",
    gender: "Female",
    status: "late",
  },
  {
    id: "ST007",
    profile: "/assets/students/student7.jpg",
    name: "James Wilson",
    gender: "Male",
    status: true,
  },
  {
    id: "ST008",
    profile: "/assets/students/student8.jpg",
    name: "Isabella Taylor",
    gender: "Female",
    status: false,
  },
];


export const classInfo: classData[] = [
  {
    code: 101,
    name: "Web Development",
    room: "A101",
    shift: "Morning",
    status: "Active",
    programType: "Bachelor",
    time: "08:00 AM - 10:00 AM",
    total_student: 35,
    female_student: 16,
  },
  {
    code: 102,
    name: "Database Systems",
    room: "B202",
    shift: "Morning",
    status: "Complete",
    programType: "Scholarship",
    time: "10:15 AM - 12:15 PM",
    total_student: 40,
    female_student: 19,
  },
  {
    code: 103,
    name: "Data Structures",
    room: "C303",
    shift: "Afternoon",
    status: "Active",
    programType: "Associate",
    time: "01:00 PM - 03:00 PM",
    total_student: 32,
    female_student: 14,
  },
  {
    code: 104,
    name: "Operating Systems",
    room: "D404",
    shift: "Afternoon",
    status: "Complete",
    programType: "Bachelor",
    time: "03:15 PM - 05:15 PM",
    total_student: 28,
    female_student: 12,
  },
  {
    code: 105,
    name: "Computer Networks",
    room: "E505",
    shift: "Evening",
    status: "Active",
    programType: "Associate",
    time: "05:30 PM - 07:30 PM",
    total_student: 45,
    female_student: 22,
  },
  {
    code: 106,
    name: "Software Engineering",
    room: "F606",
    shift: "Morning",
    status: "Complete",
    programType: "Scholarship",
    time: "08:30 AM - 10:30 AM",
    total_student: 38,
    female_student: 17,
  },
  {
    code: 107,
    name: "Cyber Security",
    room: "G707",
    shift: "Afternoon",
    status: "History",
    programType: "Bachelor",
    time: "01:30 PM - 03:30 PM",
    total_student: 30,
    female_student: 11,
  },
  {
    code: 108,
    name: "Artificial Intelligence",
    room: "H808",
    shift: "Evening",
    status: "Active",
    programType: "Scholarship",
    time: "06:00 PM - 08:00 PM",
    total_student: 25,
    female_student: 10,
  },
  {
    code: 109,
    name: "Mobile App Development",
    room: "I909",
    shift: "Morning",
    status: "Complete",
    programType: "Associate",
    time: "09:00 AM - 11:00 AM",
    total_student: 36,
    female_student: 18,
  },
  {
    code: 110,
    name: "Cloud Computing",
    room: "J010",
    shift: "Afternoon",
    status: "History",
    programType: "Bachelor",
    time: "02:00 PM - 04:00 PM",
    total_student: 42,
    female_student: 20,
  },
  {
    code: 111,
    name: "Mobile Security",
    room: "K111",
    shift: "Evening",
    status: "History",
    programType: "Associate",
    time: "07:45 PM - 09:45 PM",
    total_student: 27,
    female_student: 12,
  },
  {
    code: 112,
    name: "Cloud DevOps",
    room: "L112",
    shift: "Night",
    status: "History",
    programType: "Scholarship",
    time: "08:30 PM - 10:30 PM",
    total_student: 24,
    female_student: 10,
  },
  {
    code: 113,
    name: "Software Testing",
    room: "M113",
    shift: "Morning",
    status: "Complete",
    programType: "Bachelor",
    time: "11:00 AM - 01:00 PM",
    total_student: 31,
    female_student: 14,
  },
  {
    code: 114,
    name: "Data Analytics",
    room: "N114",
    shift: "Afternoon",
    status: "History",
    programType: "Bachelor",
    time: "04:00 PM - 06:00 PM",
    total_student: 33,
    female_student: 15,
  },
  {
    code: 115,
    name: "Frontend Engineering",
    room: "O115",
    shift: "Morning",
    status: "Active",
    programType: "Associate",
    time: "07:30 AM - 09:30 AM",
    total_student: 37,
    female_student: 18,
  },
  {
    code: 116,
    name: "System Design",
    room: "P116",
    shift: "Afternoon",
    status: "Complete",
    programType: "Bachelor",
    time: "12:30 PM - 02:30 PM",
    total_student: 34,
    female_student: 14,
  },
  {
    code: 117,
    name: "Network Administration",
    room: "Q117",
    shift: "Evening",
    status: "History",
    programType: "Scholarship",
    time: "06:30 PM - 08:30 PM",
    total_student: 26,
    female_student: 9,
  },
  {
    code: 118,
    name: "Embedded Systems",
    room: "R118",
    shift: "Night",
    status: "Active",
    programType: "Bachelor",
    time: "09:00 PM - 11:00 PM",
    total_student: 22,
    female_student: 7,
  },
  {
    code: 119,
    name: "IT Project Management",
    room: "S119",
    shift: "Morning",
    status: "Complete",
    programType: "Associate",
    time: "09:45 AM - 11:45 AM",
    total_student: 39,
    female_student: 20,
  },
  {
    code: 120,
    name: "Big Data Processing",
    room: "T120",
    shift: "Afternoon",
    status: "History",
    programType: "Scholarship",
    time: "02:45 PM - 04:45 PM",
    total_student: 29,
    female_student: 11,
  },
  {
    code: 121,
    name: "Game Development",
    room: "U121",
    shift: "Evening",
    status: "Active",
    programType: "Bachelor",
    time: "05:45 PM - 07:45 PM",
    total_student: 31,
    female_student: 13,
  },
  {
    code: 122,
    name: "Blockchain Fundamentals",
    room: "V122",
    shift: "Night",
    status: "Complete",
    programType: "Scholarship",
    time: "08:45 PM - 10:45 PM",
    total_student: 23,
    female_student: 8,
  },
];
