import { classData, Student } from "../type/classType";

export const students: Student[] = [
  {
    id: "ST001",
    profile: "/assets/students/student1.jpg",
    name: "John Doe",
    gender: "Male",
    status: true,
  },
  {
    id: "ST002",
    profile: "/assets/students/student2.jpg",
    name: "Sophia Kim",
    gender: "Female",
    status: false,
  },
  {
    id: "ST003",
    profile: "/assets/students/student3.jpg",
    name: "David Smith",
    gender: "Male",
    status: "late",
  },
  {
    id: "ST004",
    profile: "/assets/students/student4.jpg",
    name: "Emma Watson",
    gender: "Female",
    status: true,
  },
  {
    id: "ST005",
    profile: "/assets/students/student5.jpg",
    name: "Michael Lee",
    gender: "Male",
    status: false,
  },
  {
    id: "ST006",
    profile: "/assets/students/student6.jpg",
    name: "Olivia Brown",
    gender: "Female",
    status: "late",
  },
  {
    id: "ST007",
    profile: "/assets/students/student7.jpg",
    name: "James Wilson",
    gender: "Male",
    status: true,
  },
  {
    id: "ST008",
    profile: "/assets/students/student8.jpg",
    name: "Isabella Taylor",
    gender: "Female",
    status: false,
  },
];


export const classInfo: classData[] = [
  {
    code: 101,
    name: "Web Development",
    room: "A101",
    shift: "Morning",
    status: true,
    programType: "Bachelor",
    time: "08:00 AM - 10:00 AM",
    total_student: 35,
    female_student: 16,
  },
  {
    code: 102,
    name: "Database Systems",
    room: "B202",
    shift: "Morning",
    status: false,
    programType: "Scholarship",
    time: "10:15 AM - 12:15 PM",
    total_student: 40,
    female_student: 19,
  },
  {
    code: 103,
    name: "Data Structures",
    room: "C303",
    shift: "Afternoon",
    status: true,
    programType: "Associate",
    time: "01:00 PM - 03:00 PM",
    total_student: 32,
    female_student: 14,
  },
  {
    code: 104,
    name: "Operating Systems",
    room: "D404",
    shift: "Afternoon",
    status: false,
    programType: "Bachelor",
    time: "03:15 PM - 05:15 PM",
    total_student: 28,
    female_student: 12,
  },
  {
    code: 105,
    name: "Computer Networks",
    room: "E505",
    shift: "Evening",
    status: true,
    programType: "Associate",
    time: "05:30 PM - 07:30 PM",
    total_student: 45,
    female_student: 22,
  },
  {
    code: 106,
    name: "Software Engineering",
    room: "F606",
    shift: "Morning",
    status: true,
    programType: "Scholarship",
    time: "08:30 AM - 10:30 AM",
    total_student: 38,
    female_student: 17,
  },
  {
    code: 107,
    name: "Cyber Security",
    room: "G707",
    shift: "Afternoon",
    status: false,
    programType: "Bachelor",
    time: "01:30 PM - 03:30 PM",
    total_student: 30,
    female_student: 11,
  },
  {
    code: 108,
    name: "Artificial Intelligence",
    room: "H808",
    shift: "Evening",
    status: true,
    programType: "Scholarship",
    time: "06:00 PM - 08:00 PM",
    total_student: 25,
    female_student: 10,
  },
  {
    code: 109,
    name: "Mobile App Development",
    room: "I909",
    shift: "Morning",
    status: false,
    programType: "Associate",
    time: "09:00 AM - 11:00 AM",
    total_student: 36,
    female_student: 18,
  },
  {
    code: 110,
    name: "Cloud Computing",
    room: "J010",
    shift: "Afternoon",
    status: true,
    programType: "Bachelor",
    time: "02:00 PM - 04:00 PM",
    total_student: 42,
    female_student: 20,
  },
];
